[package]
name = "rust-with-your-c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_with_your_c"
crate-type = ["cdylib"]
# crate-type = ["staticlib"]

[dependencies]
